# Generated by Django 5.0.6 on 2024-07-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_following',
            field=models.BooleanField(default=False),
        ),
    ]
