# Generated by Django 5.0.6 on 2024-07-18 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_post_user_liked_profile_user_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_liked',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user_following',
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
