# Generated by Django 5.0.6 on 2024-07-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_remove_post_user_liked_remove_profile_user_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_time',
            field=models.DateTimeField(null=True),
        ),
    ]
