# Generated by Django 5.0.6 on 2024-07-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_post_edited_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
